### ISSUE TITLE
buildPeds and singletons

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedbuildr#1]
Great new library!  Below I  expected to get two
unrelated individuals (as is included in the output if allKnown=FALSE )
``` r
pedbuildr::buildPeds(ids = 1:2, sex = c(1, 1), allKnown = TRUE)
```

<sup>Created on 2018-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
Yes, but `allKnown = TRUE` requires `knownPO` to be explicitly given. I've added a check for this, so your example now gives an error message:

``` r
pedbuildr::buildPeds(ids = 1:2, sex = c(1, 1), allKnown = TRUE)
#> Error: `knownPO` cannot be NULL when `allKnown = TRUE`
```

To indicate that there are no PO relationships, use `knownPO = list()`:
``` r
library(pedbuildr)
#> Loading required package: pedtools
peds = buildPeds(ids = 1:2, sex = c(1, 1), knownPO = list(), allKnown = TRUE)
plotPeds(peds, nrow = 2)
```

![](https://i.imgur.com/GJfFKr4.png)
