### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedbuildr#2]
The suggested installation 
``` r
remotes::install_github("magnusdv/pedbuildr")
#> Error in loadNamespace(name): there is no package called 'remotes'
```
didn't work, but the standard  approach below is fine 
``` r
devtools::install_github("magnusdv/pedbuildr")
#> Skipping install of 'pedbuildr' from a github remote, the SHA1 (a1981326) has not changed since last install.
#>   Use `force = TRUE` to force installation
```

<sup>Created on 2018-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<sup>Created on 2018-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
I think the solution to this is simply to update `devtools`. That should automatically install the `remotes` package which devtools now relies on for these things.
