### ISSUE TITLE
NMBU installation problem

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedbuildr#3]
All ped-suite libraries install nicely on my laptop.
However, my colleague and I have the same problem, only with `pedbuildr`, on
our NMBU computers, apparently related to the `DESCRIPTION` file. This issue has been reported for other libraries before, but I was unable to fix based on those postings.
``` r
remotes::install_github("magnusdv/pedbuildr")
#> Error in read.dcf(path): Found continuation line starting '    person(given = " ...' at begin of record.
```

<sup>Created on 2018-12-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
I'm not able to reproduce this error, but I've seen it before. I've pushed a commit that seemed to work the last time. Could you try again now?

**Comment by thoree** [comment]
Same problem, unfortunately.
Thore

Den fre. 21. des. 2018 kl. 11:49 skrev Magnus Dehli Vigeland <
notifications@github.com>:
